/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface YoutubeVideo {
    /**
    * Explicit height of the video
    */
    'height': string;
    /**
    * The youtube video URL
    */
    'src': string;
    /**
    * Title of the video
    */
    'videoTitle': string;
    /**
    * Explicit width of the video
    */
    'width': string;
  }
}

declare global {


  interface HTMLYoutubeVideoElement extends Components.YoutubeVideo, HTMLStencilElement {}
  var HTMLYoutubeVideoElement: {
    prototype: HTMLYoutubeVideoElement;
    new (): HTMLYoutubeVideoElement;
  };
  interface HTMLElementTagNameMap {
    'youtube-video': HTMLYoutubeVideoElement;
  }
}

declare namespace LocalJSX {
  interface YoutubeVideo {
    /**
    * Explicit height of the video
    */
    'height'?: string;
    /**
    * The youtube video URL
    */
    'src': string;
    /**
    * Title of the video
    */
    'videoTitle'?: string;
    /**
    * Explicit width of the video
    */
    'width'?: string;
  }

  interface IntrinsicElements {
    'youtube-video': YoutubeVideo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'youtube-video': LocalJSX.YoutubeVideo & JSXBase.HTMLAttributes<HTMLYoutubeVideoElement>;
    }
  }
}


